version: "3.3"
services:

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    build: requierements/mariadb
    env_file: .env
    networks:
      - inception
    volumes:
      - "database_vol:/var/lib/mysql"

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build: requierements/nginx
    volumes:
      - wordpress_vol:/var/www/
    ports:
      - "443:443"
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requierements/wordpress
    env_file: .env
    volumes:
      - wordpress_vol:/var/www/
    networks:
      - inception
    restart: always

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/aleferra/docker/data/wordpress
      o: bind
  database_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/aleferra/docker/data/database
      o: bind

networks:
  inception:
    driver: bridge
