version: '3.3'
services:

  mariadb:
    build: ./requierements/mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    image: mariadb
    restart: always
    environment: 
      - .env
    networks:
      - inception
    volumes:
      - database_vol:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    build: ./requierements/wordpress
    ports:
      - "9000:9000"
    environment: 
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_vol:/var/www/
    networks:
      - inception

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build: requierements/nginx
    volumes:
      - wordpress_vol:/var/www/
    depends_on:
      - wordpress 
    ports:
      - "443:443"
    networks:
      - inception


volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/aleferra/data/wordpress
      o: bind
  database_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/aleferra/data/database
      o: bind

networks:
  inception:
    driver: bridge
