version: "3.3"
services:

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    build: 
      context: requierements/mariadb
      args:
        DB_ROOT_PASSWORD: ROOTPASSWORD
        DB_USERNAME: wpuser
        DB_PASSWORD: wppassword
        DB_DATABASE: wp_database
        WP_ROOT_USERNAME: SuperUser
        WP_ROOT_PASSWORD: SuperPassword123!
        WP_USER_PASSWORD: Motdepasse123

    environment: 
      - ./.env
    networks:
      - inception
    volumes:
      - "database_vol:/var/lib/mysql"

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    build: ./requierements/wordpress
    environment: 
      - ./.env
    depends_on:
      - mariadb
    volumes:
      - wordpress_vol:/var/www/
    networks:
      - inception

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build: requierements/nginx
    volumes:
      - wordpress_vol:/var/www/
    depends_on:
      - wordpress 
    ports:
      - "443:443"
    networks:
      - inception


volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/aleferra/docker/data/wordpress
      o: bind
  database_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/aleferra/docker/data/database
      o: bind

networks:
  inception:
    driver: bridge
